### ISSUE TITLE
Bitdefender Virus Warning

### ISSUE THREAD

**Issue by bdobson** [fabulouspanda/MacMiner#17]
I just wanted to bring this up again because the other posts are older, in 2019 virus scanners are still going crazy about this. I installed it and BitDefender went insane and I've immediately removed it from my system without a second thought. There's no way I'm running something that makes a virus scanner freak out like that. Sorry.

**Comment by fabulouspanda** [comment]
Closing since this doesn't add anything to the previous issue. If you're not comfortable with the potentially unwanted program warnings I'd recommend compiling the included binaries (cgminer, bfgminer etc. – which are what causes the warnings) on their own and if you like you can use those with MacMiner.
